export { default as NavLeft } from './NavLeft'
export { default as NavHeader } from './NavHeader'
export { default as AppMain } from './AppMain'
export { default as Page } from './Page'
export { default as TagsView } from './TagsView'
export { default as TabPage } from './TabPage'
export { default as Footer } from './Footer'
export { default as GenericListOriPage } from './GenericListPage'
export { default as GenericListPage } from './GenericListDrawerPage'
// import DrawerListTable from '@/components/Table/DrawerListTable/index'
export { default as GenericListTable } from '@/components/Table/DrawerListTable/index.vue'
export { default as GenericDetailPage } from './GenericDetailPage'
export { default as GenericCreateUpdatePage } from './GenericCreateUpdatePage'
export { default as GenericCreateUpdateForm } from './GenericCreateUpdateForm'
export { default as GenericUpdateFormDialog } from './GenericUpdateFormDialog'
export { default as GenericListTableDialog } from './GenericListTableDialog'
